server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Zensar@123
  jpa:
   hibernate:
    ddl-auto: create
  application:
     name: coupon-service
  config:
    import:
     - optional:configserver:http://localhost:8888/
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    
    service-url:
      defaulfZone: http://localhost:8761/eureka
      
  instance:
   prefer-ip-address: true 
   
#spring.config.import

      

    

  

    
 